# Pandas Exercise: Merging (MPG Cars)

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [2]:
cars1=pd.read_csv("cars1.csv")
cars2=pd.read_csv("cars2.csv")

### Step 4. Ops it seems our first dataset has some unnamed blank columns, fix cars1

In [3]:
cars1.dropna(axis=1,how='all',inplace=True)
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
168,23.0,4,140,83,2639,17.0,75,1,ford pinto
169,20.0,6,232,100,2914,16.0,75,1,amc gremlin
170,23.0,4,140,78,2592,18.5,75,1,pontiac astro
171,24.0,4,134,96,2702,13.5,75,3,toyota corona
172,25.0,4,90,71,2223,16.5,75,2,volkswagen dasher
173,24.0,4,119,97,2545,17.0,75,3,datsun 710
174,18.0,6,171,97,2984,14.5,75,1,ford pinto
175,29.0,4,90,70,1937,14.0,75,2,volkswagen rabbit
176,19.0,6,232,90,3211,17.0,75,1,amc pacer
177,23.0,4,115,95,2694,15.0,75,2,audi 100ls
178,23.0,4,120,88,2957,17.0,75,2,peugeot 504
179,22.0,4,121,98,2945,14.5,75,2,volvo 244dl
180,25.0,4,121,115,2671,13.5,75,2,saab 99le
181,33.0,4,91,53,1795,17.5,75,3,honda civic cvcc
182,28.0,4,107,86,2464,15.5,76,2,fiat 131
183,25.0,4,116,81,2220,16.9,76,2,opel 1900
184,25.0,4,140,92,2572,14.9,76,1,capri ii
185,26.0,4,98,79,2255,17.7,76,1,dodge colt
186,27.0,4,101,83,2202,15.3,76,2,renault 12tl
187,17.5,8,305,140,4215,13.0,76,1,chevrolet chevelle malibu classic
188,16.0,8,318,150,4190,13.0,76,1,dodge coronet brougham
189,15.5,8,304,120,3962,13.9,76,1,amc matador
190,14.5,8,351,152,4215,12.8,76,1,ford gran torino
191,22.0,6,225,100,3233,15.4,76,1,plymouth valiant
192,22.0,6,250,105,3353,14.5,76,1,chevrolet nova
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [4]:
print("Number of observations in cars1 : ",cars1.shape[0])
print("Number of observations in cars2 : ",cars2.shape[0])

Number of observations in cars1 :  198
Number of observations in cars2 :  200

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [5]:
frames=[cars1,cars2]
cars=pd.concat(frames,axis=0)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe
183,36.0,4,107,75,2205,14.5,82,3,honda accord
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla
185,38.0,4,91,67,1965,15.0,82,3,honda civic
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto)
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx
188,25.0,6,181,110,2945,16.4,82,1,buick century limited
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion
191,22.0,6,232,112,2835,14.7,82,1,ford granada l
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Ops there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [6]:
cars3=pd.DataFrame()
cars3['owners']=np.random.randint(15000,73000,cars.shape[0])
cars3

     owners
0     59082
1     65572
2     64009
3     31523
4     26585
5     26096
6     35007
7     65788
8     50199
9     34548
10    44969
11    37465
12    19327
13    24920
14    43953
15    50988
16    58741
17    28818
18    69980
19    35303
20    61322
21    49324
22    43833
23    50178
24    24023
25    31120
26    49013
27    41141
28    22658
29    67343
..      ...
368   68501
369   30315
370   59695
371   61421
372   47082
373   15899
374   60065
375   56687
376   48222
377   31549
378   33098
379   27532
380   37183
381   59724
382   50968
383   70737
384   65251
385   72920
386   58188
387   55601
388   20978
389   21349
390   17598
391   24497
392   50215
393   32267
394   41084
395   35015
396   63030
397   15641

[398 rows x 1 columns]

### Step 8. Add the column owners to cars

In [7]:
frames=(cars,cars3)
cars['owners']=cars3['owners']
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,59082
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,65572
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,64009
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,31523
4,17.0,8,302,140,3449,10.5,70,1,ford torino,26585
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,26096
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,35007
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,65788
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,50199
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,34548
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,44969
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,37465
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,19327
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),24920
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,43953
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,50988
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,58741
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,28818
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,69980
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,35303
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,61322
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,49324
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,43833
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,50178
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,24023
25,10.0,8,360,215,4615,14.0,70,1,ford f250,31120
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,49013
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,41141
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,22658
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,67343
...,...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,36930
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,59543
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,17407
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se,50269
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,17153
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,68764
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl,60170
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,46515
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,21904
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,29517
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,22963
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,50176
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,67072
183,36.0,4,107,75,2205,14.5,82,3,honda accord,72850
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla,42074
185,38.0,4,91,67,1965,15.0,82,3,honda civic,62275
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),36715
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,18004
188,25.0,6,181,110,2945,16.4,82,1,buick century limited,54456
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),61198
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,57077
191,22.0,6,232,112,2835,14.7,82,1,ford granada l,17699
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,50543
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,48511
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,21157
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,60353
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,29987
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,52933
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,69592
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,48101